config/routes.rb
Blog::Application.routes.draw do

  #root to: 'static_pages#home'
  root to: 'entries#index'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :entries,  only: [:show, :create, :destroy]
  resources :comments,  only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  get '/home' => 'entries#index'
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  
  get '/users' => 'users#index'
  get '/signup' =>  'users#new'
  get '/signin' =>  'sessions#new'
  get '/signout' =>  'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="http://railstutorial.org/">Rails Tutorial</a>
by Michael Hartl
</small>
<nav>
<ul>
<li><%= link_to "About",  about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
	<div class="container">
		<%= link_to "Blog", root_path, id: "logo" %>

			<nav>
			<ul class="nav pull-right">
				<% if signed_in? %>
					<li><%= link_to "Profile", current_user %></li>
					<li><%= link_to "Settings", edit_user_path(current_user) %></li>
					<li><%= link_to "People", users_path %></li>
					<li><%= link_to "Sign out", signout_path %></li>
				<% else %>
					<li><%= link_to "Sign in", signin_path %></li>
				<% end %>

			</ul>
		</nav>		
	</div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

</head>
<body>
<div>
<%= render 'layouts/header' %>
</div>

<div class="container">

<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>

</div>
<div>
<%= render 'layouts/footer' %>

	</div>
</body>
</html>